k=int(input())
l=list(map(int,input().split()))
a=int(k/2)
#print(a)
t=[]
t.append(l[0:a])
#print(t)
t.append(l[a:])
#print(t)
a,b=sum(t[0])//len(t[0]),sum(t[1])//len(t[1])
print("yes" if a==b else "no")
